{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 100000", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很牛掰的测试用例\")\n    def test_3():\n>       assert 0 > 100000\nE       assert 0 > 100000\n\ntest_1.py:22: AssertionError"}, "start": 1566181845320, "stop": 1566181845321, "uuid": "b46c29c8-6d55-4c1a-9949-25c908b277e9", "historyId": "5573ca69ec5a612ab6ebd2e4e95d945e", "fullName": "test_1#test_3", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这是一个很牛掰的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "PCL-LIWEI"}, {"name": "thread", "value": "11592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}